name: Cache Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prime cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-1bdd5c9

      - name: Verify cache step ran
        run: echo "Cache step ran"
